# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ded98a571aca9ae55bca9a25bd97cc04ed943e7b9ef2eb9e3604358eff835861a2b5b495bd5fa981fed77cc868db4185140109b19f3da5af7ff533b4f12e8e16

test:
  secret_key_base: a2dd6c945606aaa1bd2e243338f4eaec1a0461aafb1e7813834ddbcd6f9a5e76b196a3cc4f13f428f7936f8f64807e979f8d26262a1ba2686c37f613c62b67bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
